# on push to main branch build docker image from the following directory
# udagram-api-feed
# udagram-api-user
# udagram-frontend
# reverseproxy
# and push it to docker hub


services:
  - docker

before_install:
  - docker build -t "${DOCKER_USERNAME}/udagram-api-feed:v1" ./udagram-api-feed
  - docker build -t "${DOCKER_USERNAME}/udagram-api-user:v1" ./udagram-api-user
  - docker build -t "${DOCKER_USERNAME}/udagram-frontend:v2" ./udagram-frontend
  - docker build -t "${DOCKER_USERNAME}/reverseproxy:v1" ./udagram-reverseproxy

script:
  - echo "skipping tests"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "${DOCKER_USERNAME}/udagram-api-feed:v1"
  - docker push "${DOCKER_USERNAME}/udagram-api-user:v1"
  - docker push "${DOCKER_USERNAME}/udagram-frontend:v2"
  - docker push "${DOCKER_USERNAME}/reverseproxy:v1"
