# service for frontend service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8100
      targetPort: 8100
  selector:
    app: frontend